Updated cisco script

diff --git a/Switches/Cisco/Backups/backup b/Switches/Cisco/Backups/backup
--- a/Switches/Cisco/Backups/backup
+++ b/Switches/Cisco/Backups/backup
@@ -3,7 +3,7 @@
 #!/bin/bash
 
 if [[ $SSHPASS == "" ]]; then
-	cat "Error: environment variable SSHPASS not set!" 0>&2
+	echo "Error: environment variable SSHPASS not set!" 0>&2
 	exit
 fi
 
